version: '2'
services:
  db:
    build: ./db
    hostname: django_postgres
    container_name: django_postgres
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - /home/jethigh/python/django_mytweets/db/data:/var/lib/postgresql/data:rw

  web:
    build: ./web
    hostname: django_web
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code/:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
